[package]
name = "cmd_wallet"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bip39 = "2.0.0"
bitcoin = "0.31.1"
clap = "4.5.1"
rand = "0.8.5"
secp256k1 = "0.28.2"
